'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'ru' | 'uz'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    portfolio: 'Portfolio',
    analytics: 'Analytics',
    fields: 'Fields',
    settings: 'Settings',
    logout: 'Log out',
    riskAlerts: 'Risk alerts',
    language: 'Language',
    on: 'On',
    off: 'Off',
    back: 'Back',
    profileInformation: 'Profile Information',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    changePassword: 'Change Password',
    overallRiskScore: 'Overall Risk Score',
    moderate: 'Moderate',
    portfolioContains: 'Portfolio contains',
    assets: 'assets',
    assetsAtHighRisk: 'Assets at High Risk',
    totalAssets: 'Total Assets',
    portfolioValue: 'Portfolio Value',
    lastUpdate: 'Last Update',
    locationAssetDetails: 'Location & Asset Details',
    enterCoordinates: 'Enter coordinates and select crop parameters',
    step: 'Step',
    latitude: 'Latitude',
    longitude: 'Longitude',
    cropType: 'Crop Type',
    season: 'Season',
    analyze: 'Analyze',
    analyzing: 'Analyzing...',
    analysisResults: 'Analysis Results',
    viewResults: 'View Results',
    assetPortfolio: 'Asset Portfolio',
    importAssetsFromCSV: 'Import Assets from CSV',
    selectLocation: 'Select Location from Map',
    chooseCountry: 'Choose a country, region, and optional subregion',
    openInteractiveMap: 'Open Interactive Map to Select Location',
    closeMap: 'Close Map',
    selected: 'Selected',
    oldPassword: 'Old Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    updatePassword: 'Update Password',
    confidenceLevel: 'Confidence Level',
    satelliteObservations: 'Based on 47 satellite observations',
    underActiveMonitoring: 'Under active monitoring',
    totalExposure: 'Total exposure',
    valueAtRisk: 'Value at Risk',
    highRiskAssets: 'high-risk assets',
    riskDistribution: 'Risk Distribution',
    recentRiskAlerts: 'Recent Risk Alerts (Last 7 Days)',
    assetPortfolioDesc: 'Regional risk assessment and exposure management',
    importCSV: 'Import CSV',
    filterByRiskLevel: 'Filter by Risk Level',
    filterByCropType: 'Filter by Crop Type',
    allCrops: 'All Crops',
    noAssetsMatch: 'No assets match your filters',
    noData: 'No data',
    createFirstAsset: 'Create your first asset by analyzing a location in the Analytics tab or importing a CSV',
    yourFields: 'Your Fields',
    analyzedLocations: 'Analyzed locations and their risk assessments',
    location: 'Location',
    crop: 'Crop',
    riskLevel: 'Risk Level',
    viewOnMap: 'View on Map',
    goToDashboard: 'Go to Dashboard',
    welcome: 'Welcome back!',
    accessRealTime: 'Access real-time field analytics and risk insights',
    // Analytics Module
    creditRiskAnalytics: 'Credit Risk Analytics',
    enterLoanParams: 'Enter loan parameters and select the agricultural asset for risk assessment',
    loanParameters: 'Loan Parameters',
    loanAmount: 'Loan Amount (USD)',
    interestRate: 'Interest Rate (%)',
    termYears: 'Term (Years)',
    agriculturalAsset: 'Agricultural Asset',
    region: 'Region',
    district: 'District',
    selectRegion: 'Select region',
    selectDistrict: 'Select district',
    areaHectares: 'Area (Hectares)',
    runAnalysis: 'Run Analysis',
    analyzingRisk: 'Analyzing Agricultural Risk',
    processingSatellite: 'Processing satellite imagery and historical data...',
    queryingSentinel: 'Querying Sentinel-1 SAR data...',
    processingNDVI: 'Processing NDVI time series...',
    calculatingUlanova: 'Calculating Ulanova Index...',
    runningQuantile: 'Running Quantile Regression...',
    generatingRisk: 'Generating risk assessment...',
    newAnalysis: 'New Analysis',
    downloadReport: 'Download report',
    downloadReportPdf: 'Download report (PDF)',
    downloadHistoricalData: 'Download historical data',
    predictedYield: 'Predicted Yield',
    yieldAnomaly: 'Yield Anomaly',
    riskCategory: 'Risk Category',
    trendDynamics: 'Trend Dynamics',
    climateStress: 'Climate Stress',
    confidence: 'Confidence',
    ndviAnomalyTimeline: 'NDVI Anomaly Timeline',
    riskDistribution: 'Risk Distribution',
    precipVsVegetation: 'Precip vs Vegetation',
    yieldScenarioBand: 'Yield Scenario Band (P10 / P50 / P90)',
    bankingScenarioSubtitle: 'Credit stress-test scenarios: downside/base/upside yield anomaly',
    scenarioBandFootnote: 'Use P10 for conservative underwriting, P50 for base case, P90 for upside capacity.',
    dscr: 'DSCR',
    annualDebtService: 'Annual Debt Service',
    expectedRevenue: 'Expected Revenue',
    creditworthy: 'Creditworthy',
    marginal: 'Marginal',
    highDefaultRisk: 'High Default Risk',
    drawAgriculturalArea: 'Draw Agricultural Area',
    enterLoanParamsDraw: 'Enter loan parameters and draw the agricultural area on the map',
    cropCotton: 'Cotton',
    cropWheat: 'Wheat',
    cropRice: 'Rice',
    cropCorn: 'Corn',
    analysisUnavailable: 'Analysis unavailable',
    predictionServiceUnavailable: 'Prediction service unavailable. Start the backend: cd backend/services/dashboard && uvicorn app:app --port 8000',
    riskAssessment: 'Risk Assessment',
    immediateActions: 'Immediate Actions',
    seasonalOutlook: 'Seasonal Outlook',
    resourceOptimization: 'Resource Optimization',
    basedOnSatelliteData: 'Based on satellite data:',
    fieldRisk: 'Field risk',
    lowRisk: 'Low',
    moderateRisk: 'Moderate',
    highRisk: 'High',
    improving: 'Improving',
    stable: 'Stable',
    declining: 'Declining',
    detectionOfDroughtEvents: 'Detection of drought events (2015-2023)',
    districtLevelContext: 'District-level context',
    multiModalValidation: 'Multi-modal validation',
    redZoneIndicates: 'Red zone indicates anomaly < -10%. 2021 drought correctly detected.',
    regionalPattern: '40% of district fields show moderate risk. Regional pattern, not isolated.',
    rainVegetationCorrelation: 'Rain-vegetation correlation validates physics-based model.',
    aiAgriculturalAdvisor: 'AI Agricultural Advisor',
    getRecommendation: 'Get AI recommendation',
    explainKpiFallback: 'Reference explanation (AI unavailable). Set GEMINI_API_KEY in .env.local for AI responses.',
    creditRiskLabel: 'Credit risk',
    vs5YearAverage: 'vs 5-year average',
    satelliteDerived: 'Satellite-derived',
    droughtSignal: 'Drought Signal',
    normalLabel: 'Normal',
    anomalyRange: 'Anomaly range',
    trendDynamicsLabel: 'Trend Dynamics',
    addFieldToTracking: 'Add field to tracking',
    fieldAddedToTracking: 'Field added. Open the Fields tab to view.',
    satelliteEvidence: 'Satellite Evidence',
    satelliteEvidenceSubtitle: 'Satellite proof over time for this field — why the risk score makes sense',
    satelliteEvidenceDrawPolygon: 'Draw a polygon on the map and run analysis to see satellite evidence.',
    satelliteCompareMode: 'Compare Before/After',
    satelliteYear: 'Year',
    satelliteSource: 'Source',
    satelliteCloudHint: 'Cloud hint',
    satelliteNoImage: 'No image for this period',
    // Landing
    landingH1: 'Stop Gambling on Weather. Start Calculating Risk.',
    landingSub: 'AgroRisk — the first agro-scoring system in Central Asia with 80% Coverage Probability. We digitize climate risks so you protect your portfolio.',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    getStarted: 'Get Started',
    trustedBy: 'Trusted By',
    trustedByTech: 'Powered by satellite and Earth observation technologies',
    feature1Title: '24/7 Collateral Monitoring',
    feature1Desc: 'See real collateral condition even through clouds (Radar + Optical data).',
    feature2Title: 'Automated Underwriting',
    feature2Desc: 'Instant borrower assessment. We detect hidden drought and salinity risks from up to 10 years ago.',
    feature3Title: 'Precise Loss Adjustment',
    feature3Desc: 'Exact damage area without sending an agent to the field. Save on operations.',
    feature4Title: 'Bank-Grade Reliability',
    feature4Desc: 'We don\'t just give a forecast. We give a guarantee band (p10–p90) with 80% coverage accuracy.',
    howItWorks: 'How It Works',
    selectField: 'Select Field',
    chooseCrop: 'Choose Crop',
    runAnalysis: 'Run Analysis',
    getInsights: 'Get Insights',
    selectFieldDesc: 'Choose a field on our interactive map',
    chooseCropDesc: 'Specify crop type and growing season',
    runAnalysisDesc: 'Our AI models process satellite data',
    getInsightsDesc: 'Receive risk metrics and confidence bands',
    evidenceTechnicalTitle: 'Model & evidence (technical)',
    evidenceRiskScenarios: 'Risk scenarios (yield anomaly, %)',
    evidenceKeyDrivers: 'Key drivers',
    evidenceModelReliability: 'Model reliability',
    evidenceBaselineYears: 'years satellite data',
  },
  ru: {
    dashboard: 'Панель',
    portfolio: 'Портфель',
    analytics: 'Аналитика',
    fields: 'Поля',
    settings: 'Настройки',
    logout: 'Выйти',
    riskAlerts: 'Оповещения о рисках',
    language: 'Язык',
    on: 'Вкл',
    off: 'Выкл',
    back: 'Назад',
    profileInformation: 'Информация профиля',
    name: 'Имя',
    email: 'Электронная почта',
    password: 'Пароль',
    changePassword: 'Изменить пароль',
    overallRiskScore: 'Общий балл риска',
    moderate: 'Умеренный',
    portfolioContains: 'Портфель содержит',
    assets: 'активов',
    assetsAtHighRisk: 'Активы с высоким риском',
    totalAssets: 'Всего активов',
    portfolioValue: 'Стоимость портфеля',
    lastUpdate: 'Последнее обновление',
    locationAssetDetails: 'Информация о местоположении и активе',
    enterCoordinates: 'Введите координаты и выберите параметры культуры',
    step: 'Шаг',
    latitude: 'Широта',
    longitude: 'Долгота',
    cropType: 'Тип культуры',
    season: 'Сезон',
    analyze: 'Анализировать',
    analyzing: 'Анализирование...',
    analysisResults: 'Результаты анализа',
    viewResults: 'Просмотр результатов',
    assetPortfolio: 'Портфель активов',
    importAssetsFromCSV: 'Импортировать активы из CSV',
    selectLocation: 'Выберите местоположение из карты',
    chooseCountry: 'Выберите страну, регион и опциональный подрегион',
    openInteractiveMap: 'Откройте интерактивную карту для выбора местоположения',
    closeMap: 'Закрыть карту',
    selected: 'Выбрано',
    oldPassword: 'Старый пароль',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтвердите пароль',
    updatePassword: 'Обновить пароль',
    confidenceLevel: 'Уровень уверенности',
    satelliteObservations: 'На основе 47 спутниковых наблюдений',
    underActiveMonitoring: 'Под активным мониторингом',
    totalExposure: 'Общая подверженность',
    valueAtRisk: 'Стоимость под риском',
    highRiskAssets: 'активов с высоким риском',
    riskDistribution: 'Распределение рисков',
    recentRiskAlerts: 'Последние оповещения о рисках (последние 7 дней)',
    assetPortfolioDesc: 'Региональная оценка рисков и управление подверженностью',
    importCSV: 'Импортировать CSV',
    filterByRiskLevel: 'Фильтр по уровню риска',
    filterByCropType: 'Фильтр по типу культуры',
    allCrops: 'Все культуры',
    noAssetsMatch: 'Нет активов, соответствующих вашим фильтрам',
    noData: 'Нет данных',
    createFirstAsset: 'Создайте свой первый актив, анализируя местоположение на вкладке Analytics или импортируя CSV',
    yourFields: 'Ваши поля',
    analyzedLocations: 'Анализированные местоположения и оценка их рисков',
    location: 'Местоположение',
    crop: 'Культура',
    riskLevel: 'Уровень риска',
    viewOnMap: 'Просмотр на карте',
    goToDashboard: 'Перейти в панель',
    welcome: 'С возвращением!',
    accessRealTime: 'Получите доступ к аналитике полей в реальном времени и инсайты по рискам',
    // Analytics Module
    creditRiskAnalytics: 'Кредитный Риск Анализ',
    enterLoanParams: 'Введите параметры кредита и выберите сельскохозяйственный актив для оценки риска',
    loanParameters: 'Параметры кредита',
    loanAmount: 'Сумма кредита (USD)',
    interestRate: 'Процентная ставка (%)',
    termYears: 'Срок (лет)',
    agriculturalAsset: 'Сельскохозяйственный актив',
    region: 'Регион',
    district: 'Район',
    selectRegion: 'Выберите регион',
    selectDistrict: 'Выберите район',
    areaHectares: 'Площадь (гектары)',
    runAnalysis: 'Запустить анализ',
    analyzingRisk: 'Анализ сельскохозяйственного риска',
    processingSatellite: 'Обработка спутниковых снимков и исторических данных...',
    queryingSentinel: 'Запрос данных Sentinel-1 SAR...',
    processingNDVI: 'Обработка временных рядов NDVI...',
    calculatingUlanova: 'Расчет индекса Улановой...',
    runningQuantile: 'Квантильная регрессия...',
    generatingRisk: 'Генерация оценки риска...',
    newAnalysis: 'Новый анализ',
    downloadReport: 'Скачать отчёт',
    downloadReportPdf: 'Скачать отчёт (PDF)',
    downloadHistoricalData: 'Скачать исторические данные',
    predictedYield: 'Прогноз урожайности',
    yieldAnomaly: 'Аномалия урожайности',
    riskCategory: 'Категория риска',
    trendDynamics: 'Динамика тренда',
    climateStress: 'Климатический стресс',
    confidence: 'Уверенность',
    ndviAnomalyTimeline: 'Временная шкала NDVI',
    riskDistribution: 'Распределение риска',
    precipVsVegetation: 'Осадки vs Растительность',
    yieldScenarioBand: 'Сценарный диапазон урожайности (P10 / P50 / P90)',
    bankingScenarioSubtitle: 'Сценарии стресс-теста для кредита: downside / base / upside по аномалии урожая',
    scenarioBandFootnote: 'Для консервативного андеррайтинга используйте P10, для базового — P50, для апсайда — P90.',
    dscr: 'DSCR',
    annualDebtService: 'Годовое обслуживание долга',
    expectedRevenue: 'Ожидаемый доход',
    creditworthy: 'Кредитоспособен',
    marginal: 'Пограничный',
    highDefaultRisk: 'Высокий риск дефолта',
    drawAgriculturalArea: 'Нарисовать сельхозучасток',
    enterLoanParamsDraw: 'Введите параметры кредита и нарисуйте участок на карте',
    cropCotton: 'Хлопок',
    cropWheat: 'Пшеница',
    cropRice: 'Рис',
    cropCorn: 'Кукуруза',
    analysisUnavailable: 'Анализ недоступен',
    predictionServiceUnavailable: 'Сервис прогнозов недоступен. Запустите бэкенд: cd backend/services/dashboard && uvicorn app:app --port 8000',
    riskAssessment: 'Оценка риска',
    immediateActions: 'Срочные действия',
    seasonalOutlook: 'Сезонный прогноз',
    resourceOptimization: 'Оптимизация ресурсов',
    basedOnSatelliteData: 'На основе спутниковых данных:',
    fieldRisk: 'Риск поля',
    lowRisk: 'Низкий',
    moderateRisk: 'Умеренный',
    highRisk: 'Высокий',
    improving: 'Улучшение',
    stable: 'Стабильно',
    declining: 'Снижение',
    detectionOfDroughtEvents: 'Выявление засух (2015–2023)',
    districtLevelContext: 'Контекст на уровне района',
    multiModalValidation: 'Мультимодальная проверка',
    redZoneIndicates: 'Красная зона — аномалия < -10%. Засуха 2021 г. корректно выявлена.',
    regionalPattern: '40% полей района — умеренный риск. Региональная картина.',
    rainVegetationCorrelation: 'Связь осадков и растительности подтверждает модель.',
    aiAgriculturalAdvisor: 'ИИ‑агроконсультант',
    getRecommendation: 'Получить рекомендацию ИИ',
    explainKpiFallback: 'Справочное объяснение (ИИ недоступен). Задайте GEMINI_API_KEY в .env.local для ответов ИИ.',
    creditRiskLabel: 'Кредитный риск',
    vs5YearAverage: 'к 5-летней средней',
    satelliteDerived: 'По спутниковым данным',
    droughtSignal: 'Сигнал засухи',
    normalLabel: 'Норма',
    anomalyRange: 'Диапазон аномалии',
    trendDynamicsLabel: 'Динамика тренда',
    addFieldToTracking: 'Добавить поле в отслеживание',
    fieldAddedToTracking: 'Поле добавлено. Откройте вкладку Поля.',
    satelliteEvidence: 'Спутниковые доказательства',
    satelliteEvidenceSubtitle: 'Спутниковые снимки по годам для этого поля — почему оценка риска обоснована',
    satelliteEvidenceDrawPolygon: 'Нарисуйте полигон на карте и запустите анализ, чтобы увидеть спутниковые снимки.',
    satelliteCompareMode: 'Сравнить До/После',
    satelliteYear: 'Год',
    satelliteSource: 'Источник',
    satelliteCloudHint: 'Облачность',
    satelliteNoImage: 'Нет снимка за этот период',
    // Landing
    landingH1: 'Хватит гадать на погоде. Начните управлять рисками.',
    landingSub: 'AgroRisk — первая в ЦА система агро-скоринга с точностью 80% (Coverage Probability). Мы оцифровываем климатические риски, чтобы вы сохранили свой портфель.',
    signIn: 'Войти',
    signUp: 'Регистрация',
    getStarted: 'Начать',
    trustedBy: 'Нам доверяют',
    trustedByTech: 'На базе спутниковых и космических технологий',
    feature1Title: 'Мониторинг залога 24/7',
    feature1Desc: 'Видим реальное состояние залога даже сквозь облака (Radar + Optical).',
    feature2Title: 'Автоматизированный андеррайтинг',
    feature2Desc: 'Мгновенная оценка заемщика. Выявляем скрытые риски засухи и засоления за 10 лет.',
    feature3Title: 'Точное урегулирование убытков',
    feature3Desc: 'Точное определение площади ущерба без выезда агента в поле. Экономия на операционке.',
    feature4Title: 'Надёжность банковского уровня',
    feature4Desc: 'Мы не просто даём прогноз. Мы даём коридор гарантий (p10–p90) с точностью покрытия 80%.',
    howItWorks: 'Как это работает',
    selectField: 'Выбор поля',
    chooseCrop: 'Выбор культуры',
    runAnalysis: 'Запуск анализа',
    getInsights: 'Получение инсайтов',
    selectFieldDesc: 'Выберите поле на интерактивной карте',
    chooseCropDesc: 'Укажите культуру и сезон',
    runAnalysisDesc: 'ИИ обрабатывает спутниковые данные',
    getInsightsDesc: 'Получите метрики риска и доверительные интервалы',
    evidenceTechnicalTitle: 'Модель и данные (техническое)',
    evidenceRiskScenarios: 'Сценарии риска (аномалия урожая, %)',
    evidenceKeyDrivers: 'Ключевые драйверы',
    evidenceModelReliability: 'Надёжность модели',
    evidenceBaselineYears: 'лет спутниковых данных',
  },
  uz: {
    dashboard: 'Bosh sahifa',
    portfolio: 'Portfel',
    analytics: 'Tahlil',
    fields: 'Maydonlar',
    settings: 'Sozlamalar',
    logout: 'Chiqish',
    riskAlerts: 'Risk ogohilari',
    language: 'Til',
    on: 'Yoq',
    off: 'O\'chiq',
    back: 'Orqaga',
    profileInformation: 'Profil ma\'lumotlari',
    name: 'Ism',
    email: 'Email',
    password: 'Parol',
    changePassword: 'Parolni o\'zgartirish',
    overallRiskScore: 'Umumiy risk ballı',
    moderate: 'O\'rtacha',
    portfolioContains: 'Portfel o\'z ichiga oladi',
    assets: 'aktivlar',
    assetsAtHighRisk: 'Yuqori riskdagi aktivlar',
    totalAssets: 'Jami aktivlar',
    portfolioValue: 'Portfel qiymati',
    lastUpdate: 'Oxirgi yangilanish',
    locationAssetDetails: 'Joylashuv va aktiv ma\'lumotlar',
    enterCoordinates: 'Koordinatalarni kiriting va ekin parametrlarini tanlang',
    step: 'Bosqich',
    latitude: 'Kenglik',
    longitude: 'Uzunlik',
    cropType: 'Ekin turi',
    season: 'Fasl',
    analyze: 'Tahlil qilish',
    analyzing: 'Tahlil qilinmoqda...',
    analysisResults: 'Tahlil natijalari',
    viewResults: 'Natijalarni ko\'rish',
    assetPortfolio: 'Aktiv portfeli',
    importAssetsFromCSV: 'CSV dan aktivlarni import qilish',
    selectLocation: 'Xaritadan joylashuvni tanlang',
    chooseCountry: 'Mamlakatni, mintaqani va ixtiyoriy subregionni tanlang',
    openInteractiveMap: 'Joylashuvni tanlash uchun interaktiv xaritani oching',
    closeMap: 'Xaritani yoping',
    selected: 'Tanlangan',
    oldPassword: 'Eski parol',
    newPassword: 'Yangi parol',
    confirmPassword: 'Parolni tasdiqlang',
    updatePassword: 'Parolni yangilash',
    confidenceLevel: 'Ishonch darajasi',
    satelliteObservations: '47 ta sun\'iy yo\'ldosh kuzatishlari asosida',
    underActiveMonitoring: 'Faol monitoring ostida',
    totalExposure: 'Jami ta\'sir',
    valueAtRisk: 'Riskda bo\'lgan qiymat',
    highRiskAssets: 'yuqori riskli aktivlar',
    riskDistribution: 'Risk taqsimoti',
    recentRiskAlerts: 'So\'nggi risk ogohlantirish (oxirgi 7 kun)',
    assetPortfolioDesc: 'Mintaqaviy risk baholash va ta\'sir boshqaruvi',
    importCSV: 'CSV import qilish',
    filterByRiskLevel: 'Risk darajasi bo\'yicha filtr',
    filterByCropType: 'Ekin turi bo\'yicha filtr',
    allCrops: 'Barcha ekinlar',
    noAssetsMatch: 'Sizning filtrlaringizga mos aktivlar yo\'q',
    noData: 'Ma\'lumot yo\'q',
    createFirstAsset: 'Analytics yorlig\'ida lokalni tahlil qilish orqali yoki CSV import qilish orqali birinchi aktivni yarating',
    yourFields: 'Sizning maydonlaringiz',
    analyzedLocations: 'Tahlil qilingan joylashuvlar va ularning risk baholashi',
    location: 'Joylashuv',
    crop: 'Ekin',
    riskLevel: 'Risk darajasi',
    viewOnMap: 'Xaritada ko\'rish',
    goToDashboard: 'Bosh sahifaga o\'tish',
    welcome: 'Xush kelibsiz!',
    accessRealTime: 'Haqiqiy vaqtdagi maydon analitikasi va risk inayotiga kirish',
    // Analytics Module
    creditRiskAnalytics: 'Kredit Risk Tahlili',
    enterLoanParams: 'Kredit parametrlarini kiriting va risk baholash uchun qishloq xo\'jaligi aktivini tanlang',
    loanParameters: 'Kredit parametrlari',
    loanAmount: 'Kredit summasi (USD)',
    interestRate: 'Foiz stavkasi (%)',
    termYears: 'Muddat (yillar)',
    agriculturalAsset: 'Qishloq xo\'jaligi aktivi',
    region: 'Viloyat',
    district: 'Tuman',
    selectRegion: 'Viloyatni tanlang',
    selectDistrict: 'Tumanni tanlang',
    areaHectares: 'Maydon (gektar)',
    runAnalysis: 'Tahlilni boshlash',
    analyzingRisk: 'Qishloq xo\'jaligi riskini tahlil qilish',
    processingSatellite: 'Sun\'iy yo\'ldosh tasvirlari va tarixiy ma\'lumotlarni qayta ishlash...',
    queryingSentinel: 'Sentinel-1 SAR ma\'lumotlarini so\'rash...',
    processingNDVI: 'NDVI vaqt qatorlarini qayta ishlash...',
    calculatingUlanova: 'Ulanova indeksini hisoblash...',
    runningQuantile: 'Kvantil regressiyasi...',
    generatingRisk: 'Risk baholashni yaratish...',
    newAnalysis: 'Yangi tahlil',
    downloadReport: 'Hisobotni yuklash',
    downloadReportPdf: 'Hisobotni yuklash (PDF)',
    downloadHistoricalData: 'Tarixiy ma\'lumotlarni yuklash',
    predictedYield: 'Bashorat qilingan hosildorlik',
    yieldAnomaly: 'Hosildorlik anomaliyasi',
    riskCategory: 'Risk kategoriyasi',
    trendDynamics: 'Trend dinamikasi',
    climateStress: 'Iqlim stressi',
    confidence: 'Ishonch',
    ndviAnomalyTimeline: 'NDVI anomaliya jadvali',
    riskDistribution: 'Risk taqsimoti',
    precipVsVegetation: 'Yog\'in vs O\'simlik',
    yieldScenarioBand: 'Hosildorlik ssenariy diapazoni (P10 / P50 / P90)',
    bankingScenarioSubtitle: 'Kredit stress-test ssenariylari: downside / base / upside hosildorlik anomaliyasi',
    scenarioBandFootnote: 'Konservativ underwriting uchun P10, bazaviy holat uchun P50, yuqori salohiyat uchun P90.',
    dscr: 'DSCR',
    annualDebtService: 'Yillik qarz xizmati',
    expectedRevenue: 'Kutilayotgan daromad',
    creditworthy: 'Kreditga loyiq',
    marginal: 'Chegaraviy',
    highDefaultRisk: 'Yuqori defolt riski',
    drawAgriculturalArea: 'Qishloq xo\'jaligi maydonini chizing',
    enterLoanParamsDraw: 'Kredit parametrlarini kiriting va xaritada maydonni chizing',
    cropCotton: 'Paxta',
    cropWheat: 'Bug\'doy',
    cropRice: 'Guruch',
    cropCorn: 'Makka jo\'xori',
    analysisUnavailable: 'Tahlil mavjud emas',
    predictionServiceUnavailable: 'Bashorat xizmati ishlamayapti. Backend ni ishga tushiring.',
    riskAssessment: 'Risk baholashi',
    immediateActions: 'Shoshilinch choralar',
    seasonalOutlook: 'Mavsumiy prognoz',
    resourceOptimization: 'Resurslarni optimallashtirish',
    basedOnSatelliteData: 'Sun\'iy yo\'ldosh ma\'lumotlari asosida:',
    fieldRisk: 'Maydon riski',
    lowRisk: 'Past',
    moderateRisk: 'O\'rtacha',
    highRisk: 'Yuqori',
    improving: 'Yaxshilanmoqda',
    stable: 'Barqaror',
    declining: 'Pasaymoqda',
    detectionOfDroughtEvents: 'Qurg\'oqchilik aniqlash (2015–2023)',
    districtLevelContext: 'Tuman darajasi konteksti',
    multiModalValidation: 'Ko\'p rejimli tekshiruv',
    redZoneIndicates: 'Qizil zona anomaliya < -10%. 2021 qurg\'oqchilik aniqlangan.',
    regionalPattern: 'Tuman maydonlarining 40% o\'rtacha risk. Mintaqaviy naqsh.',
    rainVegetationCorrelation: 'Yog\'in-o\'simlik korrelyatsiyasi modelni tasdiqlaydi.',
    aiAgriculturalAdvisor: 'AI qishloq xo\'jaligi maslahatchisi',
    getRecommendation: 'AI tavsiyasini olish',
    explainKpiFallback: 'Ma\'lumotnoma (AI mavjud emas). GEMINI_API_KEY ni .env.local da o\'rnating.',
    creditRiskLabel: 'Kredit riski',
    vs5YearAverage: '5 yillik o\'rtachaga nisbatan',
    satelliteDerived: 'Sun\'iy yo\'ldosh ma\'lumotlari',
    droughtSignal: 'Qurg\'oqchilik signali',
    normalLabel: 'Normal',
    anomalyRange: 'Anomaliya diapazoni',
    trendDynamicsLabel: 'Trend dinamikasi',
    addFieldToTracking: 'Maydonni kuzatuvga qo\'shish',
    fieldAddedToTracking: 'Maydon qo\'shildi. Ko\'rish uchun Maydonlar yorlig\'ini oching.',
    satelliteEvidence: 'Sun\'iy yo\'ldosh dalillari',
    satelliteEvidenceSubtitle: 'Ushbu maydon bo\'yicha vaqt bo\'yicha sun\'iy yo\'ldosh tasdiqi — risk balli nima uchun mantiqiy',
    satelliteEvidenceDrawPolygon: 'Sun\'iy yo\'ldosh tasdiqini ko\'rish uchun xaritada ko\'pburchak chizing va tahlilni ishga tushiring.',
    satelliteCompareMode: 'Oldin/Keyin solishtirish',
    satelliteYear: 'Yil',
    satelliteSource: 'Manba',
    satelliteCloudHint: 'Bulutlilik',
    satelliteNoImage: 'Ushbu davr uchun rasm yo\'q',
    // Landing
    landingH1: 'Ob-havoga taslim bo\'lishni to\'xtating. Riskni hisoblang.',
    landingSub: 'AgroRisk — Markaziy Osiyoda 80% qamrov ehtimolligiga ega birinchi agro-skor tizimi. Iqlim risklarini raqamlashtiramiz, portfelingizni saqlaysiz.',
    signIn: 'Kirish',
    signUp: 'Ro\'yxatdan o\'tish',
    getStarted: 'Boshlash',
    trustedBy: 'Ishonch',
    trustedByTech: 'Sun\'iy yo\'ldosh va Yer kuzatuv texnologiyalari asosida',
    feature1Title: 'Kollateral monitoring 24/7',
    feature1Desc: 'Bulutlar orqali ham haqiqiy kollateral holatini ko\'ring (Radar + Optical).',
    feature2Title: 'Avtomatlashtirilgan underwriting',
    feature2Desc: 'Tezkor qarz oluvchi baholash. 10 yil oldingi qurg\'oqchilik va sho\'rlanish risklarini aniqlaymiz.',
    feature3Title: 'Aniq zarar tuzatish',
    feature3Desc: 'Agentni dalaga yubormasdan zarar maydonini aniqlang. Operatsiyada tejang.',
    feature4Title: 'Bank darajadagi ishonchlilik',
    feature4Desc: 'Biz nafaqat prognoz beramiz. 80% qamrov aniqligi bilan kafolatlar koridori (p10–p90) beramiz.',
    howItWorks: 'Qanday ishlaydi',
    selectField: 'Maydonni tanlash',
    chooseCrop: 'Ekinni tanlash',
    runAnalysis: 'Tahlilni boshlash',
    getInsights: 'Natijalar',
    selectFieldDesc: 'Interaktiv xaritadan maydonni tanlang',
    chooseCropDesc: 'Ekin turi va mavsumni ko\'rsating',
    runAnalysisDesc: 'AI sun\'iy yo\'ldosh ma\'lumotlarini qayta ishlaydi',
    getInsightsDesc: 'Risk metrikalari va ishonch oralig\'ini oling',
    evidenceTechnicalTitle: 'Model va ma\'lumotlar (texnik)',
    evidenceRiskScenarios: 'Risk ssenariylari (hosildorlik anomaliyasi, %)',
    evidenceKeyDrivers: 'Asosiy omillar',
    evidenceModelReliability: 'Model ishonchliligi',
    evidenceBaselineYears: 'yil sun\'iy yo\'ldosh ma\'lumotlari',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    // Get saved language preference or browser language
    const saved = localStorage.getItem('language') as Language
    if (saved && translations[saved]) {
      setLanguageState(saved)
    } else {
      // Detect browser language
      const browserLang = navigator.language.split('-')[0] as Language
      if (translations[browserLang]) {
        setLanguageState(browserLang)
      }
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
